### ISSUE TITLE
Context Menu resizes as the target resizes

### ISSUE THREAD

**Issue by MonkeyJumps** [jchristman/react-context-menus#5]
I have thumbnails that i have applied a context menu on. When I toggle the img element size the context menu scales to match the img reduction. I think the context menu should keep size and only resize because of screen viewport.

**Comment by jchristman** [comment]
Do you have screenshots of this? I’m not quite sure what you mean...

**Comment by MonkeyJumps** [comment]
sm thumbs

![image](https://user-images.githubusercontent.com/812636/33854216-b662ba30-de75-11e7-9990-d3463c45f8b2.png)



lg thumbs

![image](https://user-images.githubusercontent.com/812636/33854187-9cd09ed4-de75-11e7-8489-caa614b931d6.png)

**Comment by MonkeyJumps** [comment]
Sorry the style was being overridden. This was my fault.
